/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package document;

import finance.digana.JDBC;
import main.*;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import loan.loan_function;

/**
 *
 * @author Teran Weerasinghe
 */
public final class AddDocument extends javax.swing.JFrame {
    public final static String UI_NAME = "";
    int xmouse, ymouse;

    /**
     * Creates new form Home
     */
    public AddDocument() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/customer.jpg")));
        onLoad();

    }
    loan_function func = new loan_function();
    JDBC jdbc = new JDBC();

    private void onLoad() {
        String CID = func.getCID();
        String LOANID = func.getLOANID();
        if (!(CID.equals("")) && !(LOANID.equals(""))) {
            setData(CID, LOANID);
        } else {

        }
        loanid.setText(func.getLOANID());
    }

    private void setData(String CID, String LOANID) {
        try {
            String SQL = "SELECT * FROM customer WHERE customer_id='" + CID + "'";
            ResultSet RS = jdbc.getData(SQL);
            if (RS.next()) {
                c_name.setText(RS.getString("name_full"));
                String C_NIC = RS.getString("custoemer_nic");

                switch (C_NIC.length()) {
                    case 9:
                        C_NIC = C_NIC + "V";
                        break;
                    case 12:
                        break;
                    default:
                        C_NIC = "invalid nic please update";
                        break;
                }
                c_nic.setText(C_NIC);
                c_folderid.setText(RS.getString("folderid"));

            } else {
                JOptionPane.showMessageDialog(rootPane, "No Customer Data Found !", "ERROR", 3);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "No Customer Data Found !", "ERROR", 3);

        }
        loanid.setText(LOANID);

    }

    private void addDataTotable(String DATA) {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        Vector v = new Vector();
        v.add(DATA);
        dtm.addRow(v);
        data_field.setText("");
        data_field.grabFocus();
    }

    private void saveTableData() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int rowCount = dtm.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            saveDataToDocumentDeatailsTable(jTable1.getValueAt(i, 0).toString());
        }
    }

    private void saveDataToDocumentDeatailsTable(String DATA) {
        //status details 1=available  2=dismissed 3=returned 
        try {
            String CID = func.getCID();
            String SQL = "INSERT INTO document_details(details, status,customer_id)"
                    + "VALUES ('" + DATA + "','1','" + CID + "')";
            jdbc.putData(SQL);
            String sql = "SELECT MAX(iddocument_details) AS LastID FROM document_details;";
            ResultSet rs = jdbc.getData(sql);
            while (rs.next()) {
                String ID = rs.getString("LastID");
                saveDocumentToLoanDetails(ID);
                break;
            }

        } catch (Exception e) {
            System.out.println(e);
        }

    }

    private void saveDocumentToLoanDetails(String ID) {
        try {
            String LOANID = func.getLOANID();
            String SQL = "INSERT INTO document_loan(document_details_id, genarated_loan_id) "
                    + "VALUES ('" + ID + "','" + LOANID + "')";
            jdbc.putData(SQL);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void clearTable() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        data_field = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        c_name = new javax.swing.JLabel();
        c_nic = new javax.swing.JLabel();
        c_folderid = new javax.swing.JLabel();
        loanid = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADD DOCUMENT");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        data_field.setBackground(new java.awt.Color(57, 61, 75));
        data_field.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        data_field.setForeground(new java.awt.Color(255, 255, 255));
        data_field.setBorder(null);
        data_field.setCaretColor(new java.awt.Color(255, 255, 255));
        data_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                data_fieldKeyPressed(evt);
            }
        });
        getContentPane().add(data_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 720, 24));

        jTable1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Document Details"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 1010, 270));

        c_name.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        c_name.setForeground(new java.awt.Color(255, 255, 255));
        c_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(c_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 117, 307, 30));

        c_nic.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        c_nic.setForeground(new java.awt.Color(255, 255, 255));
        c_nic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(c_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 176, 307, 30));

        c_folderid.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        c_folderid.setForeground(new java.awt.Color(255, 255, 255));
        c_folderid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(c_folderid, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 176, 307, 30));

        loanid.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        loanid.setForeground(new java.awt.Color(255, 255, 255));
        loanid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(loanid, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 117, 307, 30));

        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(799, 240, 106, 49));

        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 606, 106, 49));

        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 606, 106, 49));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimize2.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1021, 10, 20, 20));

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1051, 10, 20, 20));

        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1083, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addDocumentBackground.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1083, 665));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        setLocation(evt.getXOnScreen() - xmouse, evt.getYOnScreen() - ymouse);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        jLabel3.setIcon(new ImageIcon(getClass().getResource("/img/close2.png")));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        jLabel3.setIcon(null);
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setIcon(null);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/img/minimize2.png")));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if (evt.getButton() == 1) {
            this.dispose();
            Home.h.setState(NORMAL);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        if (evt.getButton() == 1) {

            this.setState(ICONIFIED);

        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        sleep();
        jLabel5.setIcon(new ImageIcon(getClass().getResource("/img/refresh2.jpg")));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        sleep();
        jLabel5.setIcon(null);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        sleep();
        jLabel6.setIcon(null);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        sleep();
        jLabel6.setIcon(new ImageIcon(getClass().getResource("/img/save2.jpg")));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        sleep();
        jLabel11.setIcon(new ImageIcon(getClass().getResource("/img/add2.jpg")));
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        sleep();
        jLabel11.setIcon(null);
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        if (evt.getButton() == 1) {
            if (!(data_field.getText().equals(""))) {
                addDataTotable(data_field.getText());
            } else {
                JOptionPane.showMessageDialog(rootPane, "Enter Document Data First !");
                data_field.grabFocus();
            }
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        if (evt.getButton() == 1) {
            int I = JOptionPane.showConfirmDialog(rootPane, "Do You Want To Save !");
            if (I == 0) {
                saveTableData();
                clearTable();
                JOptionPane.showMessageDialog(rootPane, "Saved !");
            } else if (I == 2) {
                this.dispose();

            }

        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void data_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_data_fieldKeyPressed
        if (evt.getKeyCode() == 10) {
            if (!(data_field.getText().equals(""))) {
                addDataTotable(data_field.getText());
            } else {
                JOptionPane.showMessageDialog(rootPane, "Enter Document Data First !");
                data_field.grabFocus();
            }
        }
    }//GEN-LAST:event_data_fieldKeyPressed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        if (evt.getButton() == 1) {
            clearTable();
        }
    }//GEN-LAST:event_jLabel5MouseClicked
    int ml = 20;

    public void sleep() {
        try {
            Thread.sleep(ml);
        } catch (InterruptedException ex) {
            Logger.getLogger(AddDocument.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDocument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDocument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDocument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDocument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDocument().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel c_folderid;
    private javax.swing.JLabel c_name;
    private javax.swing.JLabel c_nic;
    private javax.swing.JTextField data_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel loanid;
    // End of variables declaration//GEN-END:variables
}
