/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package document;

import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import finance.digana.JDBC;
import main.*;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Teran Weerasinghe
 */
public class AttachDocument extends javax.swing.JFrame {

    JDBC jdbc;
    int xmouse, ymouse;
    public static String imageName = null;
    int customerID;
    public final static String UI_NAME = "Save Customer's Document";
    public final static String UI_NAME1 = "Delete Customer's Document";

    /**
     * Creates new form Home
     */
    public AttachDocument() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/customer.jpg")));
        docName.grabFocus();

        jdbc = JDBC.getInstance();
        loadNIC();
        AutoCompleteDecorator.decorate(jComboBox1);

    }

    private void loadNIC() {
        try {
            ResultSet rs = jdbc.getData("select custoemer_nic from customer where status='1';");
            Vector v = new Vector();
            v.add("Select Customer NIC");
            while (rs.next()) {

                v.add(rs.getString("custoemer_nic"));
            }

            jComboBox1.setModel(new DefaultComboBoxModel(v));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        AddCustomer = new javax.swing.JPanel();
        docName = new javax.swing.JTextField();
        cu_no = new javax.swing.JLabel();
        cu_name = new javax.swing.JLabel();
        cu_street = new javax.swing.JLabel();
        cu_gender = new javax.swing.JLabel();
        cu_city = new javax.swing.JLabel();
        cu_contact1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ATTACH DOCUMENT");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddCustomer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        docName.setBackground(new java.awt.Color(57, 61, 75));
        docName.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        docName.setForeground(new java.awt.Color(255, 255, 255));
        docName.setBorder(null);
        docName.setCaretColor(new java.awt.Color(255, 255, 255));
        docName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                docNameKeyTyped(evt);
            }
        });
        AddCustomer.add(docName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 340, 24));

        cu_no.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        cu_no.setForeground(new java.awt.Color(255, 255, 255));
        cu_no.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddCustomer.add(cu_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 239, 282, 30));

        cu_name.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        cu_name.setForeground(new java.awt.Color(255, 255, 255));
        cu_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddCustomer.add(cu_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 180, 282, 30));

        cu_street.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        cu_street.setForeground(new java.awt.Color(255, 255, 255));
        cu_street.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddCustomer.add(cu_street, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 239, 282, 30));

        cu_gender.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        cu_gender.setForeground(new java.awt.Color(255, 255, 255));
        cu_gender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddCustomer.add(cu_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 180, 282, 30));

        cu_city.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        cu_city.setForeground(new java.awt.Color(255, 255, 255));
        cu_city.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddCustomer.add(cu_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 239, 282, 30));

        cu_contact1.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        cu_contact1.setForeground(new java.awt.Color(255, 255, 255));
        cu_contact1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddCustomer.add(cu_contact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 180, 282, 30));

        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        AddCustomer.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 606, 106, 49));

        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        AddCustomer.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 606, 106, 49));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimize2.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        AddCustomer.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1021, 10, 20, 20));

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        AddCustomer.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1051, 10, 20, 20));

        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        AddCustomer.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1083, 70));

        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        AddCustomer.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 532, 106, 49));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        AddCustomer.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 113, 240, 28));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Document"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        AddCustomer.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 900, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/attachDocumentBack.jpg"))); // NOI18N
        AddCustomer.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(AddCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1083, 665));

        setSize(new java.awt.Dimension(1083, 665));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        setLocation(evt.getXOnScreen() - xmouse, evt.getYOnScreen() - ymouse);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        jLabel3.setIcon(new ImageIcon(getClass().getResource("/img/close2.png")));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        jLabel3.setIcon(null);
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setIcon(null);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/img/minimize2.png")));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if (evt.getButton() == 1) {
            this.dispose();
            Home.h.setState(NORMAL);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        if (evt.getButton() == 1) {

            this.setState(ICONIFIED);

        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        sleep();
        jLabel5.setIcon(new ImageIcon(getClass().getResource("/img/refresh2.jpg")));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        sleep();
        jLabel5.setIcon(null);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        sleep();
        jLabel6.setIcon(null);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        sleep();
        jLabel6.setIcon(new ImageIcon(getClass().getResource("/img/delete22.jpg")));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        if (evt.getButton() == 1) {
            if (!UserLogin.userPrivilage.contains(UI_NAME1)) {
                JOptionPane.showMessageDialog(this, "Access Denied", "Info", JOptionPane.OK_OPTION);
            } else if (customerID == 000) {
                JOptionPane.showMessageDialog(this, "Select Customer", "Info", JOptionPane.OK_OPTION);
            } else if (jTable1.getSelectedRowCount() <= 0) {
                JOptionPane.showMessageDialog(this, "Select Deocument/s", "Info", JOptionPane.OK_OPTION);
            } else if (jTable1.getSelectedRowCount() >= 1) {
                if (JOptionPane.showConfirmDialog(this, "Delete Document/s ?", "Info", JOptionPane.OK_CANCEL_OPTION) == 0) {

                    int[] rows = jTable1.getSelectedRows();
                    int status = 0;
                    for (int row : rows) {
                        int docID = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
                        try {
                            status = jdbc.putData("update document_details set status='0' where iddocument_details='" + docID + "' and customer_id='" + customerID + "'  ");
                        } catch (Exception e) {
                            e.printStackTrace();
                        }

                    }
                    loadDoc(customerID);
                    if (status == 1) {
                        JOptionPane.showMessageDialog(this, "Data Deleted", "Info", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        if (evt.getButton() == 1) {
            jComboBox1.setSelectedIndex(0);
            cu_name.setText(null);
            cu_city.setText(null);
            cu_gender.setText(null);
            cu_no.setText(null);
            cu_street.setText(null);
            ((DefaultTableModel) jTable1.getModel()).setRowCount(0);
            docName.setText(null);

            jComboBox1.showPopup();
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void docNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_docNameKeyTyped

    }//GEN-LAST:event_docNameKeyTyped

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked

        if (!UserLogin.userPrivilage.contains(UI_NAME)) {
            JOptionPane.showMessageDialog(this, "Access Denied", "Info", JOptionPane.OK_OPTION);
        } else {

            String keyword = docName.getText();
            if (customerID == 000) {
                JOptionPane.showMessageDialog(this, "Select Customer NIC", "Info", JOptionPane.OK_OPTION);
            } else if (keyword.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Enter Document Name", "Info", JOptionPane.OK_OPTION);
            } else {
                try {
                    int status = jdbc.putData("insert into document_details (details, status, customer_id) values ('" + keyword + "','1','" + customerID + "') ");
                    JOptionPane.showMessageDialog(this, "Saved", "Info", JOptionPane.INFORMATION_MESSAGE);
                    loadDoc(customerID);
                    docName.setText(null);
                    docName.grabFocus();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        sleep();
        jLabel13.setIcon(new ImageIcon(getClass().getResource("/img/save22.jpg")));
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        sleep();
        jLabel13.setIcon(null);
    }//GEN-LAST:event_jLabel13MouseExited

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String id = jComboBox1.getSelectedItem().toString();
        if (id != "Select Customer NIC") {
            try {
                ResultSet rs = jdbc.getData("select name_full,gender,contact1,no,street,city from customer where custoemer_nic = '" + id + "'   ");
                if (rs.next()) {
                    cu_name.setText(rs.getString("name_full"));
                    cu_gender.setText(rs.getString("gender"));
                    cu_contact1.setText(rs.getString("contact1"));
                    cu_no.setText(rs.getString("no"));
                    cu_street.setText(rs.getString("street"));
                    cu_city.setText(rs.getString("city"));

                }
            } catch (Exception e) {
                e.printStackTrace();
            }

            try {
                ResultSet rs = jdbc.getData("select customer_id from customer where custoemer_nic='" + id + "';");
                if (rs.next()) {
                    customerID = rs.getInt("customer_id");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

            loadDoc(customerID);

        } else {
            customerID = 000;
            cu_name.setText(null);
            cu_gender.setText(null);
            cu_contact1.setText(null);
            cu_no.setText(null);
            cu_street.setText(null);
            cu_city.setText(null);
            ((DefaultTableModel) jTable1.getModel()).setRowCount(0);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed
    private void loadDoc(int id) {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        try {
            ResultSet rs = jdbc.getData("select iddocument_details,details from document_details where customer_id='" + id + "' and status='1';");
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getInt("iddocument_details"));
                v.add(rs.getString("details"));
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    int ml = 20;

    public void sleep() {
        try {
            Thread.sleep(ml);
        } catch (InterruptedException ex) {
            Logger.getLogger(AttachDocument.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttachDocument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttachDocument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttachDocument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttachDocument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                try {
                    UIManager.setLookAndFeel(new WindowsLookAndFeel());
                } catch (Exception e) {
                }
                new AttachDocument().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddCustomer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel cu_city;
    private javax.swing.JLabel cu_contact1;
    private javax.swing.JLabel cu_gender;
    private javax.swing.JLabel cu_name;
    private javax.swing.JLabel cu_no;
    private javax.swing.JLabel cu_street;
    private javax.swing.JTextField docName;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
