/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customer;

import finance.digana.Helper;
import finance.digana.JDBC;
import image.*;
import main.*;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import loan.NewLoan;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Teran Weerasinghe
 */
public class Customer extends javax.swing.JFrame {

    JDBC jdbc;
    int xmouse, ymouse;
    public static String imageName = null;
    private int customerID = 000;
    public final static String UI_NAME = "Add Customer";
    public final static String UI_NAME1 = "Update Customer";
    public final static String UI_NAME2 = "Print Customer";
    public final static String UI_NAME3 = "Search Customer";
    public final static String UI_NAME4 = "Delete Customer";

    /**
     * Creates new form Home
     */
    public Customer() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/customer.jpg")));
        ac_initial.grabFocus();
        ac_male.setSelected(true);
        uc_male.setSelected(true);
        jdbc = JDBC.getInstance();

        UpdateCustomer.setVisible(false);
        SearchCustomer.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        table_popup = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        hiddenTable = new javax.swing.JTable();
        SearchCustomer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        rowCount = new javax.swing.JLabel();
        sc_customerImage = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        sc_keyword = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        UpdateCustomer = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        uc_customerImage = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        uc_keyword = new javax.swing.JTextField();
        uc_initial = new javax.swing.JTextField();
        uc_fullName = new javax.swing.JTextField();
        uc_nic = new javax.swing.JTextField();
        uc_no = new javax.swing.JTextField();
        uc_street = new javax.swing.JTextField();
        uc_contact1 = new javax.swing.JTextField();
        uc_contact2 = new javax.swing.JTextField();
        uc_email = new javax.swing.JTextField();
        uc_city = new javax.swing.JTextField();
        uc_special = new javax.swing.JTextField();
        uc_folderID = new javax.swing.JTextField();
        uc_male = new javax.swing.JRadioButton();
        uc_female = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        AddCustomer = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        customerImage = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ac_initial = new javax.swing.JTextField();
        ac_fullName = new javax.swing.JTextField();
        ac_nic = new javax.swing.JTextField();
        ac_no = new javax.swing.JTextField();
        ac_street = new javax.swing.JTextField();
        ac_city = new javax.swing.JTextField();
        ac_contact1 = new javax.swing.JTextField();
        ac_contact2 = new javax.swing.JTextField();
        ac_email = new javax.swing.JTextField();
        ac_special = new javax.swing.JTextField();
        ac_folderID = new javax.swing.JTextField();
        ac_male = new javax.swing.JRadioButton();
        ac_female = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem2.setText("Print Customer Detail/s");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        table_popup.add(jMenuItem2);

        hiddenTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NIC", "Initial", "Name", "Gender", "No", "Street", "City", "Contact 1", "Contact 2", "Email", "Date", "Special", "User", "FolderID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        hiddenTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hiddenTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(hiddenTable);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CUSTOMER");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchCustomer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NIC", "Initial", "Name", "Gender", "No", "Street", "City", "Contact 1", "Contact 2", "Email", "Date", "Special", "User", "FolderID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        SearchCustomer.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 830, 410));

        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        SearchCustomer.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 606, 106, 49));

        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel20MouseExited(evt);
            }
        });
        SearchCustomer.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 606, 106, 49));

        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel21MouseExited(evt);
            }
        });
        SearchCustomer.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 606, 106, 49));

        rowCount.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        rowCount.setForeground(new java.awt.Color(255, 255, 255));
        rowCount.setText("Row Count - ");
        SearchCustomer.add(rowCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, 210, 50));
        SearchCustomer.add(sc_customerImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 137, 176, 144));

        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel23MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel23MouseExited(evt);
            }
        });
        SearchCustomer.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 606, 106, 49));

        sc_keyword.setBackground(new java.awt.Color(57, 61, 75));
        sc_keyword.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        sc_keyword.setForeground(new java.awt.Color(255, 255, 255));
        sc_keyword.setBorder(null);
        sc_keyword.setCaretColor(new java.awt.Color(255, 255, 255));
        sc_keyword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sc_keywordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sc_keywordKeyTyped(evt);
            }
        });
        SearchCustomer.add(sc_keyword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 121, 350, 24));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimize2.png"))); // NOI18N
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel24MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel24MouseExited(evt);
            }
        });
        SearchCustomer.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1021, 10, 20, 20));

        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel25MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel25MouseExited(evt);
            }
        });
        SearchCustomer.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1051, 10, 20, 20));

        jLabel26.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel26MouseDragged(evt);
            }
        });
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel26MousePressed(evt);
            }
        });
        SearchCustomer.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1083, 70));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/customerSearchBackground.jpg"))); // NOI18N
        SearchCustomer.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(SearchCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1083, 665));

        UpdateCustomer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        UpdateCustomer.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 606, 106, 49));

        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel19MouseExited(evt);
            }
        });
        UpdateCustomer.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 606, 106, 49));

        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        UpdateCustomer.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 606, 106, 49));

        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        UpdateCustomer.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 407, 360, 46));
        UpdateCustomer.add(uc_customerImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 137, 176, 144));

        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });
        UpdateCustomer.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 606, 106, 49));

        uc_keyword.setBackground(new java.awt.Color(57, 61, 75));
        uc_keyword.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        uc_keyword.setForeground(new java.awt.Color(255, 255, 255));
        uc_keyword.setBorder(null);
        uc_keyword.setCaretColor(new java.awt.Color(255, 255, 255));
        uc_keyword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uc_keywordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                uc_keywordKeyTyped(evt);
            }
        });
        UpdateCustomer.add(uc_keyword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 121, 350, 24));

        uc_initial.setBackground(new java.awt.Color(57, 61, 75));
        uc_initial.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        uc_initial.setForeground(new java.awt.Color(255, 255, 255));
        uc_initial.setBorder(null);
        uc_initial.setCaretColor(new java.awt.Color(255, 255, 255));
        uc_initial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uc_initialKeyPressed(evt);
            }
        });
        UpdateCustomer.add(uc_initial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 181, 359, 24));

        uc_fullName.setBackground(new java.awt.Color(57, 61, 75));
        uc_fullName.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        uc_fullName.setForeground(new java.awt.Color(255, 255, 255));
        uc_fullName.setBorder(null);
        uc_fullName.setCaretColor(new java.awt.Color(255, 255, 255));
        uc_fullName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uc_fullNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                uc_fullNameKeyTyped(evt);
            }
        });
        UpdateCustomer.add(uc_fullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 241, 350, 24));

        uc_nic.setBackground(new java.awt.Color(57, 61, 75));
        uc_nic.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        uc_nic.setForeground(new java.awt.Color(255, 255, 255));
        uc_nic.setBorder(null);
        uc_nic.setCaretColor(new java.awt.Color(255, 255, 255));
        uc_nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                uc_nicKeyTyped(evt);
            }
        });
        UpdateCustomer.add(uc_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 301, 350, 24));

        uc_no.setBackground(new java.awt.Color(57, 61, 75));
        uc_no.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        uc_no.setForeground(new java.awt.Color(255, 255, 255));
        uc_no.setBorder(null);
        uc_no.setCaretColor(new java.awt.Color(255, 255, 255));
        uc_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uc_noKeyPressed(evt);
            }
        });
        UpdateCustomer.add(uc_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 441, 359, 24));

        uc_street.setBackground(new java.awt.Color(57, 61, 75));
        uc_street.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        uc_street.setForeground(new java.awt.Color(255, 255, 255));
        uc_street.setBorder(null);
        uc_street.setCaretColor(new java.awt.Color(255, 255, 255));
        uc_street.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uc_streetKeyPressed(evt);
            }
        });
        UpdateCustomer.add(uc_street, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 501, 359, 24));

        uc_contact1.setBackground(new java.awt.Color(57, 61, 75));
        uc_contact1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        uc_contact1.setForeground(new java.awt.Color(255, 255, 255));
        uc_contact1.setBorder(null);
        uc_contact1.setCaretColor(new java.awt.Color(255, 255, 255));
        uc_contact1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uc_contact1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                uc_contact1KeyTyped(evt);
            }
        });
        UpdateCustomer.add(uc_contact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 121, 359, 24));

        uc_contact2.setBackground(new java.awt.Color(57, 61, 75));
        uc_contact2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        uc_contact2.setForeground(new java.awt.Color(255, 255, 255));
        uc_contact2.setBorder(null);
        uc_contact2.setCaretColor(new java.awt.Color(255, 255, 255));
        uc_contact2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uc_contact2KeyPressed(evt);
            }
        });
        UpdateCustomer.add(uc_contact2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 181, 359, 24));

        uc_email.setBackground(new java.awt.Color(57, 61, 75));
        uc_email.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        uc_email.setForeground(new java.awt.Color(255, 255, 255));
        uc_email.setBorder(null);
        uc_email.setCaretColor(new java.awt.Color(255, 255, 255));
        uc_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uc_emailKeyPressed(evt);
            }
        });
        UpdateCustomer.add(uc_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 241, 359, 24));

        uc_city.setBackground(new java.awt.Color(57, 61, 75));
        uc_city.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        uc_city.setForeground(new java.awt.Color(255, 255, 255));
        uc_city.setBorder(null);
        uc_city.setCaretColor(new java.awt.Color(255, 255, 255));
        uc_city.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uc_cityKeyPressed(evt);
            }
        });
        UpdateCustomer.add(uc_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 561, 359, 24));

        uc_special.setBackground(new java.awt.Color(57, 61, 75));
        uc_special.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        uc_special.setForeground(new java.awt.Color(255, 255, 255));
        uc_special.setBorder(null);
        uc_special.setCaretColor(new java.awt.Color(255, 255, 255));
        uc_special.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uc_specialKeyPressed(evt);
            }
        });
        UpdateCustomer.add(uc_special, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 301, 359, 24));

        uc_folderID.setBackground(new java.awt.Color(57, 61, 75));
        uc_folderID.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        uc_folderID.setForeground(new java.awt.Color(255, 255, 255));
        uc_folderID.setBorder(null);
        uc_folderID.setCaretColor(new java.awt.Color(255, 255, 255));
        uc_folderID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uc_folderIDKeyPressed(evt);
            }
        });
        UpdateCustomer.add(uc_folderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 359, 359, 24));

        uc_male.setBackground(new java.awt.Color(57, 61, 75));
        buttonGroup2.add(uc_male);
        uc_male.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        uc_male.setForeground(new java.awt.Color(255, 255, 255));
        uc_male.setText("Male");
        UpdateCustomer.add(uc_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        uc_female.setBackground(new java.awt.Color(57, 61, 75));
        buttonGroup2.add(uc_female);
        uc_female.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        uc_female.setForeground(new java.awt.Color(255, 255, 255));
        uc_female.setText("Female");
        UpdateCustomer.add(uc_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimize2.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });
        UpdateCustomer.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1021, 10, 20, 20));

        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });
        UpdateCustomer.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1051, 10, 20, 20));

        jLabel17.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel17MouseDragged(evt);
            }
        });
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel17MousePressed(evt);
            }
        });
        UpdateCustomer.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1083, 70));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/customerUpdateBackground.jpg"))); // NOI18N
        UpdateCustomer.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(UpdateCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1083, 665));

        AddCustomer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        AddCustomer.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 606, 106, 49));

        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        AddCustomer.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 606, 106, 49));

        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        AddCustomer.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 407, 360, 46));
        AddCustomer.add(customerImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 137, 176, 144));

        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        AddCustomer.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 606, 106, 49));

        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        AddCustomer.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 606, 106, 49));

        ac_initial.setBackground(new java.awt.Color(57, 61, 75));
        ac_initial.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ac_initial.setForeground(new java.awt.Color(255, 255, 255));
        ac_initial.setBorder(null);
        ac_initial.setCaretColor(new java.awt.Color(255, 255, 255));
        ac_initial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ac_initialKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ac_initialKeyTyped(evt);
            }
        });
        AddCustomer.add(ac_initial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 121, 359, 24));

        ac_fullName.setBackground(new java.awt.Color(57, 61, 75));
        ac_fullName.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ac_fullName.setForeground(new java.awt.Color(255, 255, 255));
        ac_fullName.setBorder(null);
        ac_fullName.setCaretColor(new java.awt.Color(255, 255, 255));
        ac_fullName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ac_fullNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ac_fullNameKeyTyped(evt);
            }
        });
        AddCustomer.add(ac_fullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 181, 359, 24));

        ac_nic.setBackground(new java.awt.Color(57, 61, 75));
        ac_nic.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ac_nic.setForeground(new java.awt.Color(255, 255, 255));
        ac_nic.setBorder(null);
        ac_nic.setCaretColor(new java.awt.Color(255, 255, 255));
        ac_nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ac_nicKeyTyped(evt);
            }
        });
        AddCustomer.add(ac_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 241, 350, 24));

        ac_no.setBackground(new java.awt.Color(57, 61, 75));
        ac_no.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ac_no.setForeground(new java.awt.Color(255, 255, 255));
        ac_no.setBorder(null);
        ac_no.setCaretColor(new java.awt.Color(255, 255, 255));
        ac_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ac_noKeyPressed(evt);
            }
        });
        AddCustomer.add(ac_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 381, 359, 24));

        ac_street.setBackground(new java.awt.Color(57, 61, 75));
        ac_street.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ac_street.setForeground(new java.awt.Color(255, 255, 255));
        ac_street.setBorder(null);
        ac_street.setCaretColor(new java.awt.Color(255, 255, 255));
        ac_street.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ac_streetKeyPressed(evt);
            }
        });
        AddCustomer.add(ac_street, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 441, 359, 24));

        ac_city.setBackground(new java.awt.Color(57, 61, 75));
        ac_city.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ac_city.setForeground(new java.awt.Color(255, 255, 255));
        ac_city.setBorder(null);
        ac_city.setCaretColor(new java.awt.Color(255, 255, 255));
        ac_city.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ac_cityKeyPressed(evt);
            }
        });
        AddCustomer.add(ac_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 501, 359, 24));

        ac_contact1.setBackground(new java.awt.Color(57, 61, 75));
        ac_contact1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ac_contact1.setForeground(new java.awt.Color(255, 255, 255));
        ac_contact1.setBorder(null);
        ac_contact1.setCaretColor(new java.awt.Color(255, 255, 255));
        ac_contact1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ac_contact1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ac_contact1KeyTyped(evt);
            }
        });
        AddCustomer.add(ac_contact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 121, 359, 24));

        ac_contact2.setBackground(new java.awt.Color(57, 61, 75));
        ac_contact2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ac_contact2.setForeground(new java.awt.Color(255, 255, 255));
        ac_contact2.setBorder(null);
        ac_contact2.setCaretColor(new java.awt.Color(255, 255, 255));
        ac_contact2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ac_contact2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ac_contact2KeyTyped(evt);
            }
        });
        AddCustomer.add(ac_contact2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 181, 359, 24));

        ac_email.setBackground(new java.awt.Color(57, 61, 75));
        ac_email.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ac_email.setForeground(new java.awt.Color(255, 255, 255));
        ac_email.setBorder(null);
        ac_email.setCaretColor(new java.awt.Color(255, 255, 255));
        ac_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ac_emailKeyPressed(evt);
            }
        });
        AddCustomer.add(ac_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 241, 359, 24));

        ac_special.setBackground(new java.awt.Color(57, 61, 75));
        ac_special.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ac_special.setForeground(new java.awt.Color(255, 255, 255));
        ac_special.setBorder(null);
        ac_special.setCaretColor(new java.awt.Color(255, 255, 255));
        ac_special.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ac_specialKeyPressed(evt);
            }
        });
        AddCustomer.add(ac_special, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 301, 359, 24));

        ac_folderID.setBackground(new java.awt.Color(57, 61, 75));
        ac_folderID.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ac_folderID.setForeground(new java.awt.Color(255, 255, 255));
        ac_folderID.setBorder(null);
        ac_folderID.setCaretColor(new java.awt.Color(255, 255, 255));
        ac_folderID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ac_folderIDKeyPressed(evt);
            }
        });
        AddCustomer.add(ac_folderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 359, 359, 24));

        ac_male.setBackground(new java.awt.Color(57, 61, 75));
        buttonGroup1.add(ac_male);
        ac_male.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        ac_male.setForeground(new java.awt.Color(255, 255, 255));
        ac_male.setText("Male");
        AddCustomer.add(ac_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        ac_female.setBackground(new java.awt.Color(57, 61, 75));
        buttonGroup1.add(ac_female);
        ac_female.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        ac_female.setForeground(new java.awt.Color(255, 255, 255));
        ac_female.setText("Female");
        AddCustomer.add(ac_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimize2.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        AddCustomer.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1021, 10, 20, 20));

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        AddCustomer.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1051, 10, 20, 20));

        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        AddCustomer.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1083, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addCustomerBackground.jpg"))); // NOI18N
        AddCustomer.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(AddCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1083, 665));

        setSize(new java.awt.Dimension(1083, 665));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        setLocation(evt.getXOnScreen() - xmouse, evt.getYOnScreen() - ymouse);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        jLabel3.setIcon(new ImageIcon(getClass().getResource("/img/close2.png")));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        jLabel3.setIcon(null);
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setIcon(null);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/img/minimize2.png")));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if (evt.getButton() == 1) {
            this.dispose();
            Home.h.setState(NORMAL);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        if (evt.getButton() == 1) {

            this.setState(ICONIFIED);

        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        sleep();
        jLabel5.setIcon(new ImageIcon(getClass().getResource("/img/refresh2.jpg")));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        sleep();
        jLabel5.setIcon(null);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        sleep();
        jLabel6.setIcon(null);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        sleep();
        jLabel6.setIcon(new ImageIcon(getClass().getResource("/img/save2.jpg")));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        if ((evt.getButton() == 1)) {

            boolean myFlag = UserLogin.userPrivilage.contains(UI_NAME);
            if (!myFlag) {
                JOptionPane.showMessageDialog(this, "Access Denied", "Info", JOptionPane.OK_OPTION);
            } else {
                String initial = ac_initial.getText();
                String nic = ac_nic.getText();
                String fullName = ac_fullName.getText();
                String gender = (ac_male.isSelected()) ? "Male" : "Female";
                String no = ac_no.getText();
                String street = ac_street.getText();
                String city = ac_city.getText();
                String contact1 = ac_contact1.getText();
                String contact2 = ac_contact2.getText();
                String email = ac_email.getText();
                String specialNote = ac_special.getText();
                String folderID = ac_folderID.getText();

                if (initial.isEmpty() || nic.isEmpty() | fullName.isEmpty() || no.isEmpty() || street.isEmpty() || city.isEmpty() || contact1.isEmpty() | contact2.isEmpty() | email.isEmpty() | specialNote.isEmpty() | folderID.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Fill All Details", "Info", JOptionPane.OK_OPTION);
                } else if (contact1.length() != 10) {
                    JOptionPane.showMessageDialog(this, "Check Contact 1 Length", "Info", JOptionPane.OK_OPTION);
                    ac_contact1.grabFocus();
                    ac_contact1.selectAll();
                } else if (contact2.length() != 10) {
                    JOptionPane.showMessageDialog(this, "Check Contact 2 Length", "Info", JOptionPane.OK_OPTION);
                    ac_contact2.grabFocus();
                    ac_contact2.selectAll();
                } else if (imageName == null) {
                    JOptionPane.showMessageDialog(this, "Please Capture Image", "Info", JOptionPane.OK_OPTION);
                } else {
                    boolean flag = true;
                    try {
                        ResultSet rs = jdbc.getData("select customer_id from customer where custoemer_nic ='" + nic + "' and status = 1; ");
                        while (rs.next()) {
                            flag = false;
                            break;
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                    if (flag) {

                        if (JOptionPane.showConfirmDialog(this, "New Customer ?", "Info", JOptionPane.OK_CANCEL_OPTION) == 0) {
                            String date = Helper.getDateAndTime("date");
                            String time = Helper.getDateAndTime("time");
                            try {
                                int status = jdbc.putData("insert into customer (custoemer_nic, name_full, name_ini, gender, no, street, city, contact1, contact2, email, addedDate, addedTime, status, specialNote, folderid, user_user_id,imageName) values ('" + nic + "','" + fullName + "','" + initial + "','" + gender + "','" + no + "','" + street + "','" + city + "','" + contact1 + "','" + contact2 + "','" + email + "','" + date + "','" + time + "','1','" + specialNote + "','" + folderID + "','" + UserLogin.userID + "','" + imageName + "') ");
                                if (status == 1) {
                                    JOptionPane.showMessageDialog(this, "Data Saved", "Info", JOptionPane.INFORMATION_MESSAGE);
                                    refreshCustomerAdd();
                                    
                                    
                                    int myStatus = JOptionPane.showConfirmDialog(this, "Redirect To Loan ?");
                                    if(myStatus == 0){
                                        
                                        new NewLoan(nic).setVisible(true);
                                    }
                                    //
                                    //
                                    // CODE INSERT HERE
                                    //
                                    //
                                    
                                    
                                    
                                }
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Duplicate NIC", "Info", JOptionPane.OK_OPTION);
                    }
                }
            }
        }
    }//GEN-LAST:event_jLabel6MouseClicked
    private void refreshCustomerAdd() {
        ac_initial.setText(null);
        ac_fullName.setText(null);
        ac_nic.setText(null);
        ac_no.setText(null);
        ac_street.setText(null);
        ac_city.setText(null);
        ac_contact1.setText(null);
        ac_contact2.setText(null);
        ac_email.setText(null);
        ac_special.setText(null);
        ac_folderID.setText(null);
        ac_male.setSelected(true);
        customerImage.setIcon(null);
        ac_initial.grabFocus();

    }
    private void ac_folderIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ac_folderIDKeyPressed
        if (evt.getKeyCode() == 10) {
            if (ac_nic.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Enter NIC", "Info", JOptionPane.OK_OPTION);
            } else {
                ac_folderID.setText("CF - " + ac_nic.getText());
            }
        }
    }//GEN-LAST:event_ac_folderIDKeyPressed

    private void ac_nicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ac_nicKeyTyped
        Helper.validationTextfield(evt, "number");
    }//GEN-LAST:event_ac_nicKeyTyped

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered

        sleep();
        jLabel7.setIcon(new ImageIcon(getClass().getResource("/img/cImage2.jpg")));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        sleep();
        jLabel7.setIcon(null);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        if (evt.getButton() == 1) {
            new ImageCapture().run();
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        if (evt.getButton() == 1) {
            refreshCustomerAdd();
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        if (evt.getButton() == 1) {
            refreshCustomerAdd();
            AddCustomer.setVisible(false);
            UpdateCustomer.setVisible(true);
            SearchCustomer.setVisible(false);
            uc_keyword.grabFocus();
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        sleep();
        jLabel8.setIcon(new ImageIcon(getClass().getResource("/img/goUpdate.jpg")));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        sleep();
        jLabel8.setIcon(null);
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        if (evt.getButton() == 1) {
            sc_keyword.grabFocus();
            SearchCustomer.setVisible(true);
            AddCustomer.setVisible(false);
            UpdateCustomer.setVisible(false);
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        sleep();
        jLabel9.setIcon(new ImageIcon(getClass().getResource("/img/goSearch.jpg")));
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        sleep();
        jLabel9.setIcon(null);
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        if (evt.getButton() == 1) {
            refreshUpdate();
        }
    }//GEN-LAST:event_jLabel10MouseClicked
    void refreshUpdate() {
        uc_initial.setText(null);
        uc_fullName.setText(null);
        uc_nic.setText(null);
        uc_no.setText(null);
        uc_street.setText(null);
        uc_city.setText(null);
        uc_contact1.setText(null);
        uc_contact2.setText(null);
        uc_email.setText(null);
        uc_keyword.setText(null);
        uc_special.setText(null);
        uc_folderID.setText(null);
        uc_male.setSelected(true);
        uc_customerImage.setIcon(null);
        uc_keyword.grabFocus();
    }
    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        sleep();
        jLabel10.setIcon(new ImageIcon(getClass().getResource("/img/refresh2.jpg")));
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        sleep();
        jLabel10.setIcon(null);
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        if (evt.getButton() == 1) {

            boolean myFlag = UserLogin.userPrivilage.contains(UI_NAME1);
            if (!myFlag) {
                JOptionPane.showMessageDialog(this, "Access Denied", "Info", JOptionPane.OK_OPTION);
            } else if (customerID == 000) {
                JOptionPane.showMessageDialog(this, "No User", "Info", JOptionPane.OK_OPTION);
            } else {
                String initial = uc_initial.getText();
                String fullName = uc_fullName.getText();
                String nic = uc_nic.getText();
                String no = uc_no.getText();
                String street = uc_street.getText();
                String city = uc_city.getText();
                String contact1 = uc_contact1.getText();
                String contact2 = uc_contact2.getText();
                String email = uc_email.getText();
                String special = uc_special.getText();
                String folderID = uc_folderID.getText();
                String gender = (uc_male.isSelected()) ? "Male" : "Female";

                if (initial.isEmpty() || nic.isEmpty() | fullName.isEmpty() || no.isEmpty() || street.isEmpty() || city.isEmpty() || contact1.isEmpty() | contact2.isEmpty() | email.isEmpty() | special.isEmpty() | folderID.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Fill All Details", "Info", JOptionPane.OK_OPTION);
                } else if (contact1.length() != 10) {
                    JOptionPane.showMessageDialog(this, "Check Contact 1 Length", "Info", JOptionPane.OK_OPTION);
                    uc_contact1.grabFocus();
                    uc_contact1.selectAll();
                } else if (contact2.length() != 10) {
                    JOptionPane.showMessageDialog(this, "Check Contact 2 Length", "Info", JOptionPane.OK_OPTION);
                    uc_contact2.grabFocus();
                    uc_contact2.selectAll();
                } else {

                    boolean flag = true;
                    try {
                        ResultSet rs = jdbc.getData("select customer_id from customer where custoemer_nic='" + nic + "' and customer_id != '" + customerID + "' and status='1' ");
                        if (rs.next()) {
                            flag = false;
                        }

                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                    if (flag && (JOptionPane.showConfirmDialog(this, "UpdateCustomer ?", "Info", JOptionPane.OK_CANCEL_OPTION) == 0)) {
                        try {
                            String sql = "update customer set custoemer_nic='" + nic + "', name_full='" + fullName + "', name_ini='" + initial + "', gender='" + gender + "', no='" + no + "', street='" + street + "', city='" + city + "', contact1='" + contact1 + "', contact2='" + contact2 + "', email='" + email + "', specialNote='" + special + "', folderid='" + folderID + "', imageName='" + imageName + "' where customer_id='" + customerID + "'  ";
                            int status = jdbc.putData(sql);
                            if (status == 1) {
                                JOptionPane.showMessageDialog(this, "Data Updated", "Info", JOptionPane.INFORMATION_MESSAGE);
                                refreshUpdate();
                            }
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Duplicate NIC", "Info", JOptionPane.OK_OPTION);

                    }

                }

            }

        }
    }//GEN-LAST:event_jLabel11MouseClicked
    private void refreshCustomerUpdate() {

    }
    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        sleep();
        jLabel11.setIcon(new ImageIcon(getClass().getResource("/img/update2.jpg")));
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        sleep();
        jLabel11.setIcon(null);
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        if (evt.getButton() == 1) {
            if (customerID == 000) {
                JOptionPane.showMessageDialog(this, "No User", "Info", JOptionPane.OK_OPTION);
            } else {
                new ImageCapture1().run();
            }

        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        sleep();
        jLabel12.setIcon(new ImageIcon(getClass().getResource("/img/updateImage.jpg")));
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        sleep();
        jLabel12.setIcon(null);
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        if (evt.getButton() == 1) {
            ac_initial.grabFocus();
            AddCustomer.setVisible(true);
            SearchCustomer.setVisible(false);
            UpdateCustomer.setVisible(false);
        }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        sleep();
        jLabel14.setIcon(new ImageIcon(getClass().getResource("/img/goAdd.jpg")));
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        sleep();
        jLabel14.setIcon(null);
    }//GEN-LAST:event_jLabel14MouseExited

    private void uc_fullNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uc_fullNameKeyTyped
        Helper.validationTextfield(evt, "text");
    }//GEN-LAST:event_uc_fullNameKeyTyped

    private void uc_folderIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uc_folderIDKeyPressed
        if (evt.getKeyCode() == 10) {
            if (uc_nic.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Enter NIC", "Info", JOptionPane.OK_OPTION);
            } else {
                uc_folderID.setText("CF - " + uc_nic.getText());
            }
        }
    }//GEN-LAST:event_uc_folderIDKeyPressed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        if (evt.getButton() == 1) {
            setState(ICONIFIED);
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        jLabel15.setIcon(new ImageIcon(getClass().getResource("/img/minimize2.png")));
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        jLabel15.setIcon(null);
    }//GEN-LAST:event_jLabel15MouseExited

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        if (evt.getButton() == 1) {
            this.dispose();
            Home.h.setState(NORMAL);
        }
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        jLabel16.setIcon(new ImageIcon(getClass().getResource("/img/close2.png")));
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        jLabel16.setIcon(null);
    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel17MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseDragged
        setLocation(evt.getXOnScreen() - xmouse, evt.getYOnScreen() - ymouse);
    }//GEN-LAST:event_jLabel17MouseDragged

    private void jLabel17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MousePressed
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_jLabel17MousePressed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        if (evt.getButton() == 1) {
            AddCustomer.setVisible(false);
            SearchCustomer.setVisible(true);
            UpdateCustomer.setVisible(false);
            sc_keyword.grabFocus();
        }
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseEntered
        sleep();
        jLabel19.setIcon(new ImageIcon(getClass().getResource("/img/goSearch.jpg")));
    }//GEN-LAST:event_jLabel19MouseEntered

    private void jLabel19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseExited
        sleep();
        jLabel19.setIcon(null);
    }//GEN-LAST:event_jLabel19MouseExited

    private void uc_keywordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uc_keywordKeyPressed
        if (evt.getKeyCode() == 10) {
            String keyword = uc_keyword.getText();
            if (keyword.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Enter Keyword", "Info", JOptionPane.OK_OPTION);
                uc_keyword.grabFocus();
            } else {
                try {
                    String sql = "select * from customer where custoemer_nic LIKE '%" + keyword + "%' and status='1';";
                    ResultSet rs = jdbc.getData(sql);
                    if (rs.next()) {

                        customerID = rs.getInt("customer_id");

                        uc_initial.setText(rs.getString("name_ini"));
                        uc_fullName.setText(rs.getString("name_full"));
                        uc_nic.setText(rs.getString("custoemer_nic"));
                        uc_no.setText(rs.getString("no"));
                        uc_street.setText(rs.getString("street"));
                        uc_city.setText(rs.getString("city"));
                        uc_contact1.setText(rs.getString("contact1"));
                        uc_contact2.setText(rs.getString("contact2"));
                        uc_email.setText(rs.getString("email"));
                        uc_special.setText(rs.getString("specialNote"));
                        uc_folderID.setText(rs.getString("folderid"));

                        if (rs.getString("gender").equalsIgnoreCase("male")) {
                            uc_male.setSelected(true);
                        } else {
                            uc_female.setSelected(true);
                        }

                        String path = null;

                        try {
                            path = new File(".").getCanonicalPath();
                        } catch (IOException ex) {
                            ex.printStackTrace();
                        }

                        imageName = rs.getString("imageName");

                        String fullName = path + "\\" + imageName;
                        uc_customerImage.setIcon(new ImageIcon(fullName));

                    } else {
                        JOptionPane.showMessageDialog(this, "Not Found", "Info", JOptionPane.OK_OPTION);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_uc_keywordKeyPressed

    private void uc_nicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uc_nicKeyTyped
        Helper.validationTextfield(evt, "number");

    }//GEN-LAST:event_uc_nicKeyTyped

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        if (evt.getButton() == 1) {
            refreshSearch();
        }
    }//GEN-LAST:event_jLabel13MouseClicked
    private void refreshSearch() {
        ((DefaultTableModel) jTable1.getModel()).setRowCount(0);
        sc_keyword.setText(null);
        rowCount.setText("Row Count - ");
        sc_customerImage.setIcon(null);
        sc_keyword.grabFocus();
    }
    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        sleep();
        jLabel13.setIcon(new ImageIcon(getClass().getResource("/img/refresh2.jpg")));
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        sleep();
        jLabel13.setIcon(null);
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        if (evt.getButton() == 1) {
            SearchCustomer.setVisible(false);
            AddCustomer.setVisible(false);
            UpdateCustomer.setVisible(true);
            uc_keyword.grabFocus();
        }
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseEntered
        sleep();
        jLabel20.setIcon(new ImageIcon(getClass().getResource("/img/goUpdate.jpg")));
    }//GEN-LAST:event_jLabel20MouseEntered

    private void jLabel20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseExited
        sleep();
        jLabel20.setIcon(null);
    }//GEN-LAST:event_jLabel20MouseExited

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        if (evt.getButton() == 1) {
            if (!UserLogin.userPrivilage.contains(UI_NAME4)) {
                JOptionPane.showMessageDialog(this, "Access Denied", "Info", JOptionPane.OK_OPTION);
            } else if ((jTable1.getSelectedRowCount() > 0) && (JOptionPane.showConfirmDialog(this, "Delete Customer ?", "Info", JOptionPane.OK_CANCEL_OPTION) == 0)) {
                int rows[] = jTable1.getSelectedRows();
                boolean flag = true;
                for (int row : rows) {
                    int customerID = Integer.parseInt(jTable1.getValueAt(row, 0).toString());

                    try {
                        ResultSet rs = jdbc.getData("select * from loan where customer_id='" + customerID + "' ");
                        if (rs.next()) {
                            flag = false;
                        } else {
                            jdbc.putData("update customer set status='0' where customer_id='" + customerID + "';");
                        }

                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }

                if (flag) {
                    JOptionPane.showMessageDialog(this, "Deleted. \n Some Customers Not Deleted !!", "Info", JOptionPane.INFORMATION_MESSAGE);
                    refreshSearch();
                } else {

                    JOptionPane.showMessageDialog(this, "Data Deleted", "Info", JOptionPane.INFORMATION_MESSAGE);
                    refreshSearch();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please Select User / Users", "Info", JOptionPane.OK_OPTION);
            }
        }
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseEntered
        sleep();
        jLabel21.setIcon(new ImageIcon(getClass().getResource("/img/delete2.jpg")));
    }//GEN-LAST:event_jLabel21MouseEntered

    private void jLabel21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseExited
        sleep();
        jLabel21.setIcon(null);
    }//GEN-LAST:event_jLabel21MouseExited

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        if (evt.getButton() == 1) {
            SearchCustomer.setVisible(false);
            AddCustomer.setVisible(true);
            UpdateCustomer.setVisible(false);
            ac_initial.grabFocus();
        }
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseEntered
        sleep();
        jLabel23.setIcon(new ImageIcon(getClass().getResource("/img/goAdd.jpg")));
    }//GEN-LAST:event_jLabel23MouseEntered

    private void jLabel23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseExited
        sleep();
        jLabel23.setIcon(null);
    }//GEN-LAST:event_jLabel23MouseExited

    private void sc_keywordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sc_keywordKeyPressed
        if (evt.getKeyCode() == 10) {
            if (!UserLogin.userPrivilage.contains(UI_NAME3)) {
                JOptionPane.showMessageDialog(this, "Access Denied", "Info", JOptionPane.OK_OPTION);
            } else {
                String keyword = sc_keyword.getText();
                if (keyword.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Enter Keyword", "Info", JOptionPane.OK_OPTION);
                    sc_keyword.grabFocus();
                } else {
                    ResultSet rs = null;
                    DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                    dtm.setRowCount(0);
                    rowCount.setText("Row Count - ");
                    try {
                        String sql = null;
                        if (keyword == "0000") {
                            sql = "select * from customer where custoemer_nic LIKE '%" + keyword + "%' and status='1';";
                        } else {
                            sql = "select * from customer where status='1';";
                        }

                        rs = jdbc.getData(sql);
                        while (rs.next()) {
                            Vector vector = new Vector();
                            vector.add(rs.getInt("customer_id"));
                            vector.add(rs.getString("custoemer_nic"));
                            vector.add(rs.getString("name_ini"));
                            vector.add(rs.getString("name_full"));
                            vector.add(rs.getString("gender"));
                            vector.add(rs.getString("no"));
                            vector.add(rs.getString("street"));
                            vector.add(rs.getString("city"));
                            vector.add(rs.getString("contact1"));
                            vector.add(rs.getString("contact2"));
                            vector.add(rs.getString("email"));
                            vector.add(rs.getString("addedDate"));
                            vector.add(rs.getString("specialNote"));

                            ResultSet rs2 = jdbc.getData("select name,status from user where user_id = '" + rs.getInt("user_user_id") + "'  ");
                            if (rs2.next()) {
                                if (rs2.getBoolean("status")) {
                                    vector.add(rs2.getString("name"));
                                } else {
                                    vector.add(rs2.getString("name") + "(DELETED)");
                                }
                            }
                            vector.add(rs.getString("folderid"));

                            dtm.addRow(vector);

                        }

                        rowCount.setText("Row Count - " + jTable1.getRowCount());
                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                    if (rs == null) {
                        JOptionPane.showMessageDialog(this, "Not Found", "Info", JOptionPane.OK_OPTION);
                    }

                }
            }
        }
    }//GEN-LAST:event_sc_keywordKeyPressed

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        if (evt.getButton() == 1) {
            setState(ICONIFIED);
        }
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseEntered
        jLabel24.setIcon(new ImageIcon(getClass().getResource("/img/minimize2.png")));
    }//GEN-LAST:event_jLabel24MouseEntered

    private void jLabel24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseExited
        jLabel24.setIcon(null);
    }//GEN-LAST:event_jLabel24MouseExited

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        if (evt.getButton() == 1) {
            this.dispose();
            Home.h.setState(NORMAL);
        }
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseEntered
        jLabel25.setIcon(new ImageIcon(getClass().getResource("/img/close2.png")));
    }//GEN-LAST:event_jLabel25MouseEntered

    private void jLabel25MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseExited
        jLabel25.setIcon(null);
    }//GEN-LAST:event_jLabel25MouseExited

    private void jLabel26MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseDragged
        setLocation(evt.getXOnScreen() - xmouse, evt.getYOnScreen() - ymouse);
    }//GEN-LAST:event_jLabel26MouseDragged

    private void jLabel26MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MousePressed
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_jLabel26MousePressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (jTable1.getSelectedRowCount() == 1) {
            int userID = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            String imageName = null;
            try {
                ResultSet rs = jdbc.getData("select imageName from customer where customer_id='" + userID + "';");
                if (rs.next()) {
                    String path = null;

                    try {
                        path = new File(".").getCanonicalPath();
                    } catch (IOException ex) {
                        ex.printStackTrace();
                    }

                    imageName = rs.getString("imageName");

                    String fullName = path + "\\" + imageName;
                    sc_customerImage.setIcon(new ImageIcon(fullName));
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            sc_customerImage.setIcon(null);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void uc_keywordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uc_keywordKeyTyped
        Helper.validationTextfield(evt, "number");
    }//GEN-LAST:event_uc_keywordKeyTyped

    private void uc_contact1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uc_contact1KeyTyped
        Helper.validationTextfield(evt, "number");
        if (uc_contact1.getText().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_uc_contact1KeyTyped

    private void ac_fullNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ac_fullNameKeyTyped
        Helper.validationTextfield(evt, "text");
    }//GEN-LAST:event_ac_fullNameKeyTyped

    private void ac_contact1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ac_contact1KeyTyped
        Helper.validationTextfield(evt, "number");
        if (ac_contact1.getText().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_ac_contact1KeyTyped

    private void ac_contact2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ac_contact2KeyTyped
        Helper.validationTextfield(evt, "number");
        if (ac_contact2.getText().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_ac_contact2KeyTyped

    private void sc_keywordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sc_keywordKeyTyped
        Helper.validationTextfield(evt, "number");
    }//GEN-LAST:event_sc_keywordKeyTyped

    private void ac_initialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ac_initialKeyTyped

    }//GEN-LAST:event_ac_initialKeyTyped

    private void ac_initialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ac_initialKeyPressed
        if (evt.getKeyCode() == 10) {
            ac_fullName.grabFocus();
        }
    }//GEN-LAST:event_ac_initialKeyPressed

    private void ac_fullNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ac_fullNameKeyPressed
        if (evt.getKeyCode() == 10) {
            ac_nic.grabFocus();
        }
    }//GEN-LAST:event_ac_fullNameKeyPressed

    private void ac_noKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ac_noKeyPressed
        if (evt.getKeyCode() == 10) {
            ac_street.grabFocus();
        }
    }//GEN-LAST:event_ac_noKeyPressed

    private void ac_streetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ac_streetKeyPressed
        if (evt.getKeyCode() == 10) {
            ac_city.grabFocus();
        }
    }//GEN-LAST:event_ac_streetKeyPressed

    private void ac_cityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ac_cityKeyPressed
        if (evt.getKeyCode() == 10) {
            ac_contact1.grabFocus();
        }
    }//GEN-LAST:event_ac_cityKeyPressed

    private void ac_contact1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ac_contact1KeyPressed
        if (evt.getKeyCode() == 10) {
            ac_contact2.grabFocus();
        }
    }//GEN-LAST:event_ac_contact1KeyPressed

    private void ac_contact2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ac_contact2KeyPressed
        if (evt.getKeyCode() == 10) {
            ac_email.grabFocus();
        }
    }//GEN-LAST:event_ac_contact2KeyPressed

    private void ac_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ac_emailKeyPressed
        if (evt.getKeyCode() == 10) {
            ac_special.grabFocus();
        }
    }//GEN-LAST:event_ac_emailKeyPressed

    private void ac_specialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ac_specialKeyPressed
        if (evt.getKeyCode() == 10) {
            ac_folderID.grabFocus();
        }
    }//GEN-LAST:event_ac_specialKeyPressed

    private void uc_initialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uc_initialKeyPressed
        if (evt.getKeyCode() == 10) {
            uc_fullName.grabFocus();
        }
    }//GEN-LAST:event_uc_initialKeyPressed

    private void uc_fullNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uc_fullNameKeyPressed
        if (evt.getKeyCode() == 10) {
            uc_nic.grabFocus();
        }
    }//GEN-LAST:event_uc_fullNameKeyPressed

    private void uc_noKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uc_noKeyPressed
        if (evt.getKeyCode() == 10) {
            uc_street.grabFocus();
        }
    }//GEN-LAST:event_uc_noKeyPressed

    private void uc_streetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uc_streetKeyPressed
        if (evt.getKeyCode() == 10) {
            uc_city.grabFocus();
        }
    }//GEN-LAST:event_uc_streetKeyPressed

    private void uc_cityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uc_cityKeyPressed
        if (evt.getKeyCode() == 10) {
            uc_contact1.grabFocus();
        }
    }//GEN-LAST:event_uc_cityKeyPressed

    private void uc_contact1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uc_contact1KeyPressed
        if (evt.getKeyCode() == 10) {
            uc_contact2.grabFocus();
        }
    }//GEN-LAST:event_uc_contact1KeyPressed

    private void uc_contact2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uc_contact2KeyPressed
        if (evt.getKeyCode() == 10) {
            uc_email.grabFocus();
        }
    }//GEN-LAST:event_uc_contact2KeyPressed

    private void uc_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uc_emailKeyPressed
        if (evt.getKeyCode() == 10) {
            uc_special.grabFocus();
        }
    }//GEN-LAST:event_uc_emailKeyPressed

    private void uc_specialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uc_specialKeyPressed
        if (evt.getKeyCode() == 10) {
            uc_folderID.grabFocus();
        }
    }//GEN-LAST:event_uc_specialKeyPressed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int[] rows = jTable1.getSelectedRows();
        
        if (!UserLogin.userPrivilage.contains(UI_NAME2)) {
            JOptionPane.showMessageDialog(this, "Access Denied", "Info", JOptionPane.OK_OPTION);
        } else if (rows.length <= 0) {
            JOptionPane.showMessageDialog(this, "Please Select Row/s", "Info", JOptionPane.OK_OPTION);
        } 

        
        else if(rows.length > 0) {
            try {

                DefaultTableModel dtm = (DefaultTableModel) hiddenTable.getModel();
                dtm.setRowCount(0);
                //if (rows.length == 1) {
                    
               
                
                for(int row:rows){

                    Vector v = new Vector();

                    v.add(jTable1.getValueAt(row, 0));
                    v.add(jTable1.getValueAt(row, 1));
                    v.add(jTable1.getValueAt(row, 2));
                    v.add(jTable1.getValueAt(row, 3));
                    v.add(jTable1.getValueAt(row, 4));
                    v.add(jTable1.getValueAt(row, 5));
                    v.add(jTable1.getValueAt(row, 6));
                    v.add(jTable1.getValueAt(row, 7));
                    v.add(jTable1.getValueAt(row, 8));
                    v.add(jTable1.getValueAt(row, 9));
                    v.add(jTable1.getValueAt(row, 10));
                    v.add(jTable1.getValueAt(row, 11));
                    v.add(jTable1.getValueAt(row, 12));
                    v.add(jTable1.getValueAt(row, 13));
                    v.add(jTable1.getValueAt(row, 14));

                    dtm.addRow(v);
                }

                
                
                
                String path = new File(".").getCanonicalPath();

                path += "\\report\\CustomerDetails.jrxml";

                String shopName = null;
                String shopAddress = null;
                String shopContact = null;
                String shopEmail = null;

                ResultSet rs = jdbc.getData("select * from shopdetails where idshopDetails='1';");
                if (rs.next()) {

                    shopName = rs.getString("shopName");
                    shopAddress = rs.getString("shopAddress");
                    shopContact = rs.getString("shopContact");
                    shopEmail = rs.getString("shopEmail");

                }

                JasperReport jr = JasperCompileManager.compileReport(path);

                Map<String, Object> parameters = new HashMap<String, Object>();
                parameters.put("date", Helper.getDateAndTime("date"));
                parameters.put("time", Helper.getDateAndTime("time"));

                parameters.put("shopName", shopName);
                parameters.put("shopAddress", shopAddress);
                parameters.put("shopContact", shopContact);
                parameters.put("shopEmail", shopEmail);

                rs = jdbc.getData("select name,status from user where user_id = '" + UserLogin.userID + "';");
                if (rs.next()) {
                    boolean status = rs.getBoolean("status");
                    if (status) {
                        parameters.put("user", rs.getString("name"));
                    } else {
                        parameters.put("user", rs.getString("name") + "(DELETED)");
                    }
                }

                parameters.put("RCount", rows.length);

                JasperPrint jp = JasperFillManager.fillReport(jr, parameters, new JRTableModelDataSource(hiddenTable.getModel()));
                JasperViewer.viewReport(jp, false);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void hiddenTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hiddenTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_hiddenTableMouseClicked
    private int row;
    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        if (evt.getButton() == 3) {
            row = jTable1.getSelectedRow();
        }
    }//GEN-LAST:event_jTable1MousePressed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        if (!(row < 0)) {
            if (evt.isPopupTrigger()) {

                table_popup.show(jTable1, evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jTable1MouseReleased
    int ml = 20;

    public void sleep() {
        try {
            Thread.sleep(ml);
        } catch (InterruptedException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddCustomer;
    private javax.swing.JPanel SearchCustomer;
    private javax.swing.JPanel UpdateCustomer;
    private javax.swing.JTextField ac_city;
    private javax.swing.JTextField ac_contact1;
    private javax.swing.JTextField ac_contact2;
    private javax.swing.JTextField ac_email;
    private javax.swing.JRadioButton ac_female;
    private javax.swing.JTextField ac_folderID;
    private javax.swing.JTextField ac_fullName;
    private javax.swing.JTextField ac_initial;
    private javax.swing.JRadioButton ac_male;
    private javax.swing.JTextField ac_nic;
    private javax.swing.JTextField ac_no;
    private javax.swing.JTextField ac_special;
    private javax.swing.JTextField ac_street;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public static javax.swing.JLabel customerImage;
    private javax.swing.JTable hiddenTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel rowCount;
    public static javax.swing.JLabel sc_customerImage;
    private javax.swing.JTextField sc_keyword;
    private javax.swing.JPopupMenu table_popup;
    private javax.swing.JTextField uc_city;
    private javax.swing.JTextField uc_contact1;
    private javax.swing.JTextField uc_contact2;
    public static javax.swing.JLabel uc_customerImage;
    private javax.swing.JTextField uc_email;
    private javax.swing.JRadioButton uc_female;
    private javax.swing.JTextField uc_folderID;
    private javax.swing.JTextField uc_fullName;
    private javax.swing.JTextField uc_initial;
    private javax.swing.JTextField uc_keyword;
    private javax.swing.JRadioButton uc_male;
    private javax.swing.JTextField uc_nic;
    private javax.swing.JTextField uc_no;
    private javax.swing.JTextField uc_special;
    private javax.swing.JTextField uc_street;
    // End of variables declaration//GEN-END:variables
}
