/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import com.sun.jndi.toolkit.ctx.HeadTail;
import customer.Customer;
import finance.digana.Helper;
import finance.digana.JDBC;
import java.awt.Toolkit;
import java.io.File;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import loan.NewLoan;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Teran Weerasinghe
 */
public class Past extends javax.swing.JFrame {

    JDBC jdbc;
    public final static String UI_NAME = "Add Past Records";
    public final static String UI_NAME1 = "Delete Past Records";
    public final static String UI_NAME2 = "Search Past Records";
    public final static String UI_NAME3 = "Update Past Records";
    public final static String UI_NAME4 = "Print Past Records";

    /**
     * Creates new form Past
     */
    public Past() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/home.png")));
        male.setSelected(true);
        jdbc = JDBC.getInstance();

        getAll();

    }

    private void getAll() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        try {
            String sql = "select * from pastrecord ;";
            ResultSet rs = jdbc.getData(sql);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getInt("id"));
                v.add(rs.getString("nic"));
                v.add(rs.getString("fname"));
                v.add(rs.getString("mname"));
                v.add(rs.getString("lname"));

                if (rs.getString("gender").equalsIgnoreCase("male")) {
                    v.add("Male");
                } else {
                    v.add("Female");
                }

                v.add(rs.getString("contact1"));
                v.add(rs.getString("contact2"));
                v.add(rs.getString("contact3"));
                v.add(rs.getString("no"));
                v.add(rs.getString("street"));
                v.add(rs.getString("city"));
                v.add(rs.getString("loneID"));
                v.add(rs.getString("loneRange"));
                v.add(rs.getString("loneAmount"));
                v.add(rs.getString("paidAmount"));
                v.add(rs.getString("specialNote"));
                v.add(rs.getString("date"));
                v.add(rs.getString("total"));

                dtm.addRow(v);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        table_popup = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        val = new javax.swing.JScrollPane();
        hiddenTable = new javax.swing.JTable();
        totalplusint = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        nic = new javax.swing.JTextField();
        special = new javax.swing.JTextField();
        contact3 = new javax.swing.JTextField();
        loneid = new javax.swing.JTextField();
        lonerange = new javax.swing.JTextField();
        no = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        contact1 = new javax.swing.JTextField();
        street = new javax.swing.JTextField();
        loneamount = new javax.swing.JTextField();
        mname = new javax.swing.JTextField();
        paidamount = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        contact2 = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        keyword = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem2.setText("Print Details/s");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        table_popup.add(jMenuItem2);

        jMenuItem3.setText("Add As New Loan");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseClicked(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        table_popup.add(jMenuItem3);

        hiddenTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NIC", "First Name", "Mid Name", "Last Name", "Gender", "Contact 1", "Contact 2", "Document Type", "No", "Street", "City", "Lone ID", "Lone Range", "Lone Amount", "Paid Amount", "Special Note", "Date", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        hiddenTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hiddenTableMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hiddenTableMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hiddenTableMouseClicked(evt);
            }
        });
        val.setViewportView(hiddenTable);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Let's Insert Past Records");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalplusint.setBackground(new java.awt.Color(57, 61, 75));
        totalplusint.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        totalplusint.setForeground(new java.awt.Color(255, 255, 255));
        totalplusint.setBorder(null);
        totalplusint.setCaretColor(new java.awt.Color(255, 255, 255));
        totalplusint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalplusintKeyTyped(evt);
            }
        });
        getContentPane().add(totalplusint, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 272, 245, 24));

        date.setBackground(new java.awt.Color(57, 61, 75));
        date.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setBorder(null);
        date.setCaretColor(new java.awt.Color(255, 255, 255));
        date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dateKeyTyped(evt);
            }
        });
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 272, 245, 24));

        nic.setBackground(new java.awt.Color(57, 61, 75));
        nic.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        nic.setForeground(new java.awt.Color(255, 255, 255));
        nic.setBorder(null);
        nic.setCaretColor(new java.awt.Color(255, 255, 255));
        nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nicKeyTyped(evt);
            }
        });
        getContentPane().add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 41, 245, 24));

        special.setBackground(new java.awt.Color(57, 61, 75));
        special.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        special.setForeground(new java.awt.Color(255, 255, 255));
        special.setBorder(null);
        special.setCaretColor(new java.awt.Color(255, 255, 255));
        special.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                specialKeyTyped(evt);
            }
        });
        getContentPane().add(special, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 102, 245, 24));

        contact3.setBackground(new java.awt.Color(57, 61, 75));
        contact3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        contact3.setForeground(new java.awt.Color(255, 255, 255));
        contact3.setBorder(null);
        contact3.setCaretColor(new java.awt.Color(255, 255, 255));
        contact3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contact3KeyTyped(evt);
            }
        });
        getContentPane().add(contact3, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 152, 245, 24));

        loneid.setBackground(new java.awt.Color(57, 61, 75));
        loneid.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        loneid.setForeground(new java.awt.Color(255, 255, 255));
        loneid.setBorder(null);
        loneid.setCaretColor(new java.awt.Color(255, 255, 255));
        loneid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                loneidKeyTyped(evt);
            }
        });
        getContentPane().add(loneid, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 212, 245, 24));

        lonerange.setBackground(new java.awt.Color(57, 61, 75));
        lonerange.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lonerange.setForeground(new java.awt.Color(255, 255, 255));
        lonerange.setBorder(null);
        lonerange.setCaretColor(new java.awt.Color(255, 255, 255));
        lonerange.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lonerangeKeyTyped(evt);
            }
        });
        getContentPane().add(lonerange, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 212, 245, 24));

        no.setBackground(new java.awt.Color(57, 61, 75));
        no.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        no.setForeground(new java.awt.Color(255, 255, 255));
        no.setBorder(null);
        no.setCaretColor(new java.awt.Color(255, 255, 255));
        no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noKeyTyped(evt);
            }
        });
        getContentPane().add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 152, 245, 24));

        fname.setBackground(new java.awt.Color(57, 61, 75));
        fname.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        fname.setForeground(new java.awt.Color(255, 255, 255));
        fname.setBorder(null);
        fname.setCaretColor(new java.awt.Color(255, 255, 255));
        fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnameKeyTyped(evt);
            }
        });
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 41, 245, 24));

        contact1.setBackground(new java.awt.Color(57, 61, 75));
        contact1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        contact1.setForeground(new java.awt.Color(255, 255, 255));
        contact1.setBorder(null);
        contact1.setCaretColor(new java.awt.Color(255, 255, 255));
        contact1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contact1KeyTyped(evt);
            }
        });
        getContentPane().add(contact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 102, 245, 24));

        street.setBackground(new java.awt.Color(57, 61, 75));
        street.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        street.setForeground(new java.awt.Color(255, 255, 255));
        street.setBorder(null);
        street.setCaretColor(new java.awt.Color(255, 255, 255));
        street.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                streetKeyTyped(evt);
            }
        });
        getContentPane().add(street, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 152, 245, 24));

        loneamount.setBackground(new java.awt.Color(57, 61, 75));
        loneamount.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        loneamount.setForeground(new java.awt.Color(255, 255, 255));
        loneamount.setBorder(null);
        loneamount.setCaretColor(new java.awt.Color(255, 255, 255));
        loneamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                loneamountKeyTyped(evt);
            }
        });
        getContentPane().add(loneamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 212, 245, 24));

        mname.setBackground(new java.awt.Color(57, 61, 75));
        mname.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        mname.setForeground(new java.awt.Color(255, 255, 255));
        mname.setBorder(null);
        mname.setCaretColor(new java.awt.Color(255, 255, 255));
        mname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mnameKeyTyped(evt);
            }
        });
        getContentPane().add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 41, 245, 24));

        paidamount.setBackground(new java.awt.Color(57, 61, 75));
        paidamount.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        paidamount.setForeground(new java.awt.Color(255, 255, 255));
        paidamount.setBorder(null);
        paidamount.setCaretColor(new java.awt.Color(255, 255, 255));
        paidamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paidamountKeyTyped(evt);
            }
        });
        getContentPane().add(paidamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(956, 212, 245, 24));

        city.setBackground(new java.awt.Color(57, 61, 75));
        city.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        city.setForeground(new java.awt.Color(255, 255, 255));
        city.setBorder(null);
        city.setCaretColor(new java.awt.Color(255, 255, 255));
        city.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cityKeyTyped(evt);
            }
        });
        getContentPane().add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(956, 152, 245, 24));

        contact2.setBackground(new java.awt.Color(57, 61, 75));
        contact2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        contact2.setForeground(new java.awt.Color(255, 255, 255));
        contact2.setBorder(null);
        contact2.setCaretColor(new java.awt.Color(255, 255, 255));
        contact2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contact2KeyTyped(evt);
            }
        });
        getContentPane().add(contact2, new org.netbeans.lib.awtextra.AbsoluteConstraints(956, 102, 245, 24));

        lname.setBackground(new java.awt.Color(57, 61, 75));
        lname.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lname.setForeground(new java.awt.Color(255, 255, 255));
        lname.setBorder(null);
        lname.setCaretColor(new java.awt.Color(255, 255, 255));
        lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lnameKeyTyped(evt);
            }
        });
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(956, 41, 245, 24));

        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(834, 619, 106, 49));

        keyword.setBackground(new java.awt.Color(57, 61, 75));
        keyword.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        keyword.setForeground(new java.awt.Color(255, 255, 255));
        keyword.setBorder(null);
        keyword.setCaretColor(new java.awt.Color(255, 255, 255));
        keyword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keywordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                keywordKeyTyped(evt);
            }
        });
        getContentPane().add(keyword, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 292, 245, 24));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NIC", "First Name", "Mid Name", "Last Name", "Gender", "Contact 1", "Contact 2", "Document Type", "No", "Street", "City", "Lone ID", "Lone Range", "Lone Amount", "Paid Amount", "Special Note", "Date", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 1280, 270));

        female.setBackground(new java.awt.Color(57, 61, 75));
        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        getContentPane().add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));

        male.setBackground(new java.awt.Color(57, 61, 75));
        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("Male");
        getContentPane().add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(955, 619, 106, 49));

        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1073, 619, 106, 49));

        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1194, 619, 106, 49));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pastRecords.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicKeyTyped
        Helper.validationTextfield(evt, "number");
    }//GEN-LAST:event_nicKeyTyped

    private void specialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_specialKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_specialKeyTyped

    private void contact3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contact3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_contact3KeyTyped

    private void loneidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loneidKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_loneidKeyTyped

    private void lonerangeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lonerangeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_lonerangeKeyTyped

    private void noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_noKeyTyped

    private void fnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameKeyTyped

    private void contact1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contact1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_contact1KeyTyped

    private void streetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_streetKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_streetKeyTyped

    private void loneamountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loneamountKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_loneamountKeyTyped

    private void mnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_mnameKeyTyped

    private void paidamountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paidamountKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_paidamountKeyTyped

    private void cityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cityKeyTyped

    private void contact2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contact2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_contact2KeyTyped

    private void lnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameKeyTyped

    private void keywordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keywordKeyTyped

    }//GEN-LAST:event_keywordKeyTyped

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        if (evt.getButton() == 1) {
            refresh();
        }
    }//GEN-LAST:event_jLabel5MouseClicked
    int ml = 20;

    public void sleep() {
        try {
            Thread.sleep(ml);
        } catch (InterruptedException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        sleep();
        jLabel5.setIcon(new ImageIcon(getClass().getResource("/img/refresh2.jpg")));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        sleep();
        jLabel5.setIcon(null);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        if (evt.getButton() == 1) {
            if (!UserLogin.userPrivilage.contains(UI_NAME)) {
                JOptionPane.showMessageDialog(this, "Access Denied", "Info", JOptionPane.OK_OPTION);
            } else {
                String pnic = nic.getText();
                String pspecial = special.getText();
                String pcontact1 = contact1.getText();
                String pcontact2 = contact2.getText();
                String pcontact3 = contact3.getText();
                String ploneid = loneid.getText();
                String plonerange = lonerange.getText();
                String ploneamount = loneamount.getText();
                String ppaidamount = paidamount.getText();
                String pfname = fname.getText();
                String plname = lname.getText();
                String pmname = mname.getText();
                String pno = no.getText();
                String pstreet = street.getText();
                String pcity = city.getText();
                String gender = (male.isSelected()) ? "Male" : "Female";
                String manualDate = date.getText();
                String totalpint = totalplusint.getText();

                if (pnic.isEmpty() || manualDate.isEmpty() || totalpint.isEmpty() || pspecial.isEmpty() || pcontact1.isEmpty() || pcontact2.isEmpty() || pcontact3.isEmpty() || ploneid.isEmpty() || plonerange.isEmpty() || ploneamount.isEmpty() || ppaidamount.isEmpty() || pfname.isEmpty() || plname.isEmpty() || pmname.isEmpty() || pno.isEmpty() || pstreet.isEmpty() || pcity.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Fill All Details", "Info", JOptionPane.OK_OPTION);
                } else if (JOptionPane.showConfirmDialog(this, "New Record/s ?", "Info", JOptionPane.OK_CANCEL_OPTION) == 0) {
                    try {
                        int status = jdbc.putData("insert into pastrecord ( nic, fname, mname, lname, gender, contact1, contact2, contact3, no, street, city, loneID, loneRange, loneAmount, paidAmount, specialNote,date,total) values ('" + pnic + "','" + pfname + "','" + pmname + "','" + plname + "','" + gender + "','" + pcontact1 + "','" + pcontact2 + "','" + pcontact3 + "','" + pno + "','" + pstreet + "','" + pcity + "','" + ploneid + "','" + plonerange + "','" + ploneamount + "','" + ppaidamount + "','" + pspecial + "','" + manualDate + "','" + totalpint + "')   ");
                        if (status == 1) {
                            JOptionPane.showMessageDialog(this, "Saved", "Info", JOptionPane.INFORMATION_MESSAGE);
                            refresh();
                            getAll();
                        } else {
                            JOptionPane.showMessageDialog(this, "Try Again!", "Info", JOptionPane.OK_OPTION);
                        }

                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }

        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        sleep();
        jLabel6.setIcon(new ImageIcon(getClass().getResource("/img/save2.jpg")));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        sleep();
        jLabel6.setIcon(null);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        if (!UserLogin.userPrivilage.contains(UI_NAME1)) {
            JOptionPane.showMessageDialog(this, "Access Denied", "Info", JOptionPane.OK_OPTION);
        } else if ((evt.getButton() == 1) && (jTable1.getSelectedRowCount() >= 1)) {
            if (JOptionPane.showConfirmDialog(this, "Delete Record/s ?", "Info", JOptionPane.OK_CANCEL_OPTION) == 0) {
                int rows[] = jTable1.getSelectedRows();
                int status = 0;
                for (int row : rows) {
                    int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
                    try {
                        status = jdbc.putData("delete from pastrecord where id='" + id + "'");
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }

                if (status == 1) {
                    JOptionPane.showMessageDialog(this, "Data Deleted", "Info", JOptionPane.OK_OPTION);
                    refresh();
                }

            }

        } else {
            JOptionPane.showMessageDialog(this, "Select Record Row /  Rows", "Info", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        sleep();
        jLabel7.setIcon(new ImageIcon(getClass().getResource("/img/delete2.jpg")));
    }//GEN-LAST:event_jLabel7MouseEntered
    void refresh() {
        keyword.setText(null);
        ((DefaultTableModel) jTable1.getModel()).setRowCount(0);
        nic.setText(null);
        special.setText(null);
        contact1.setText(null);
        contact2.setText(null);
        contact3.setText(null);
        no.setText(null);
        street.setText(null);
        city.setText(null);
        fname.setText(null);
        mname.setText(null);
        lname.setText(null);
        loneid.setText(null);
        lonerange.setText(null);
        loneamount.setText(null);
        paidamount.setText(null);
        male.setSelected(true);
        date.setText(null);
        totalplusint.setText(null);
        nic.grabFocus();
    }
    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        sleep();
        jLabel7.setIcon(null);
    }//GEN-LAST:event_jLabel7MouseExited

    private void keywordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keywordKeyPressed
        if (evt.getKeyCode() == 10) {
            if (!UserLogin.userPrivilage.contains(UI_NAME2)) {
                JOptionPane.showMessageDialog(this, "Access Denied", "Info", JOptionPane.OK_OPTION);
            } else {
                String userKeyword = keyword.getText();

                if (userKeyword.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Enter NIC", "Info", JOptionPane.OK_OPTION);
                } else if (userKeyword.equalsIgnoreCase("all")) {
                    getAll();
                } else {

                    DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                    dtm.setRowCount(0);
                    try {
                        String sql = "select * from pastrecord where nic LIKE '%" + userKeyword + "%' OR fname LIKE '%" + userKeyword + "%' OR mname LIKE '%" + userKeyword + "%' OR lname LIKE '%" + userKeyword + "%' ;";
                        ResultSet rs = jdbc.getData(sql);
                        while (rs.next()) {
                            Vector v = new Vector();
                            v.add(rs.getInt("id"));
                            v.add(rs.getString("nic"));
                            v.add(rs.getString("fname"));
                            v.add(rs.getString("mname"));
                            v.add(rs.getString("lname"));

                            if (rs.getString("gender").equalsIgnoreCase("male")) {
                                v.add("Male");
                            } else {
                                v.add("Female");
                            }

                            v.add(rs.getString("contact1"));
                            v.add(rs.getString("contact2"));
                            v.add(rs.getString("contact3"));
                            v.add(rs.getString("no"));
                            v.add(rs.getString("street"));
                            v.add(rs.getString("city"));
                            v.add(rs.getString("loneID"));
                            v.add(rs.getString("loneRange"));
                            v.add(rs.getString("loneAmount"));
                            v.add(rs.getString("paidAmount"));
                            v.add(rs.getString("specialNote"));
                            v.add(rs.getString("date"));
                            v.add(rs.getString("total"));

                            dtm.addRow(v);

                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        }
    }//GEN-LAST:event_keywordKeyPressed

    private void dateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateKeyTyped
        
    }//GEN-LAST:event_dateKeyTyped

    private void totalplusintKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalplusintKeyTyped
       
    }//GEN-LAST:event_totalplusintKeyTyped
    int cuID = 000;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (jTable1.getSelectedRowCount() == 1) {
            int row = jTable1.getSelectedRow();
            cuID = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
            nic.setText(jTable1.getValueAt(row, 1).toString());
            fname.setText(jTable1.getValueAt(row, 2).toString());
            mname.setText(jTable1.getValueAt(row, 3).toString());
            lname.setText(jTable1.getValueAt(row, 4).toString());

            if (jTable1.getValueAt(row, 5).toString().equalsIgnoreCase("male")) {
                male.setSelected(true);
            } else {
                female.setSelected(true);
            }
            
            contact1.setText(jTable1.getValueAt(row, 6).toString());
            contact2.setText(jTable1.getValueAt(row, 7).toString());
            contact3.setText(jTable1.getValueAt(row, 8).toString());
            no.setText(jTable1.getValueAt(row, 9).toString());
            street.setText(jTable1.getValueAt(row, 10).toString());
            city.setText(jTable1.getValueAt(row, 11).toString());
            loneid.setText(jTable1.getValueAt(row, 12).toString());
            lonerange.setText(jTable1.getValueAt(row, 13).toString());
            loneamount.setText(jTable1.getValueAt(row, 14).toString());
            paidamount.setText(jTable1.getValueAt(row, 15).toString());
            special.setText(jTable1.getValueAt(row, 16).toString());
            date.setText(jTable1.getValueAt(row, 17).toString());
            totalplusint.setText(jTable1.getValueAt(row, 18).toString());
            

        }else{
            cuID = 000;
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
         sleep();
        jLabel8.setIcon(new ImageIcon(getClass().getResource("/img/Udate.jpg")));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        sleep();
        jLabel8.setIcon(null);
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        if (evt.getButton() == 1) {
            if(jTable1.getSelectedRowCount() == 0){
                JOptionPane.showMessageDialog(this, "Please Select Row", "Info", JOptionPane.OK_OPTION);
            }
            else{
                if (!UserLogin.userPrivilage.contains(UI_NAME3)) {
                JOptionPane.showMessageDialog(this, "Access Denied", "Info", JOptionPane.OK_OPTION);
            } else {
                String pnic = nic.getText();
                String pspecial = special.getText();
                String pcontact1 = contact1.getText();
                String pcontact2 = contact2.getText();
                String pcontact3 = contact3.getText();
                String ploneid = loneid.getText();
                String plonerange = lonerange.getText();
                String ploneamount = loneamount.getText();
                String ppaidamount = paidamount.getText();
                String pfname = fname.getText();
                String plname = lname.getText();
                String pmname = mname.getText();
                String pno = no.getText();
                String pstreet = street.getText();
                String pcity = city.getText();
                String gender = (male.isSelected()) ? "Male" : "Female";
                String manualDate = date.getText();
                String totalpint = totalplusint.getText();

                if (pnic.isEmpty() || manualDate.isEmpty() || totalpint.isEmpty() || pspecial.isEmpty() || pcontact1.isEmpty() || pcontact2.isEmpty() || pcontact3.isEmpty() || ploneid.isEmpty() || plonerange.isEmpty() || ploneamount.isEmpty() || ppaidamount.isEmpty() || pfname.isEmpty() || plname.isEmpty() || pmname.isEmpty() || pno.isEmpty() || pstreet.isEmpty() || pcity.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Fill All Details", "Info", JOptionPane.OK_OPTION);
                } else if (JOptionPane.showConfirmDialog(this, "Update Past Record ?", "Info", JOptionPane.OK_CANCEL_OPTION) == 0) {
                    try {
                        int status = jdbc.putData("update  pastrecord set nic='" + pnic + "', fname='" + pfname + "', mname='" + pmname + "', lname='" + plname + "', gender='" + gender + "', contact1='" + pcontact1 + "', contact2='" + pcontact2 + "', contact3='" + pcontact3 + "', no='" + pno + "', street='" + pstreet + "', city='" + pcity + "', loneID='" + ploneid + "', loneRange='" + plonerange + "', loneAmount='" + ploneamount + "', paidAmount='" + ppaidamount + "', specialNote='" + pspecial + "',date='" + manualDate + "',total='" + totalpint + "' where id = '"+cuID+"';   ");
                        if (status == 1) {
                            JOptionPane.showMessageDialog(this, "Updated", "Info", JOptionPane.INFORMATION_MESSAGE);
                            refresh();
                            getAll();
                        } else {
                            JOptionPane.showMessageDialog(this, "Try Again!", "Info", JOptionPane.OK_OPTION);
                        }

                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
            }

        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int[] rows = jTable1.getSelectedRows();

        if (!UserLogin.userPrivilage.contains(UI_NAME4)) {
            JOptionPane.showMessageDialog(this, "Access Denied", "Info", JOptionPane.OK_OPTION);
        } else if (rows.length <= 0) {
            JOptionPane.showMessageDialog(this, "Please Select Row/s", "Info", JOptionPane.OK_OPTION);
        }
       

        else if(rows.length > 0) {
            try {

                DefaultTableModel dtm = (DefaultTableModel) hiddenTable.getModel();
                dtm.setRowCount(0);
                

                    for(int row:rows){

                        Vector v = new Vector();

                        v.add(jTable1.getValueAt(row, 0));
                        v.add(jTable1.getValueAt(row, 1));
                        v.add(jTable1.getValueAt(row, 2));
                        v.add(jTable1.getValueAt(row, 3));
                        v.add(jTable1.getValueAt(row, 4));
                        v.add(jTable1.getValueAt(row, 5));
                        v.add(jTable1.getValueAt(row, 6));
                        v.add(jTable1.getValueAt(row, 7));
                        v.add(jTable1.getValueAt(row, 8));
                        v.add(jTable1.getValueAt(row, 9));
                        v.add(jTable1.getValueAt(row, 10));
                        v.add(jTable1.getValueAt(row, 11));
                        v.add(jTable1.getValueAt(row, 12));
                        v.add(jTable1.getValueAt(row, 13));
                        v.add(jTable1.getValueAt(row, 14));
                        v.add(jTable1.getValueAt(row, 15));
                        v.add(jTable1.getValueAt(row, 16));
                        v.add(jTable1.getValueAt(row, 17));
                        v.add(jTable1.getValueAt(row, 18));

                        dtm.addRow(v);
                    }
                 

                String path = new File(".").getCanonicalPath();

                path += "\\report\\PastRecord.jrxml";

                String shopName = null;
                String shopAddress = null;
                String shopContact = null;
                String shopEmail = null;

                ResultSet rs = jdbc.getData("select * from shopdetails where idshopDetails='1';");
                if (rs.next()) {

                    shopName = rs.getString("shopName");
                    shopAddress = rs.getString("shopAddress");
                    shopContact = rs.getString("shopContact");
                    shopEmail = rs.getString("shopEmail");

                }

                JasperReport jr = JasperCompileManager.compileReport(path);

                Map<String, Object> parameters = new HashMap<String, Object>();
                parameters.put("date", Helper.getDateAndTime("date"));
                parameters.put("time", Helper.getDateAndTime("time"));

                parameters.put("shopName", shopName);
                parameters.put("shopAddress", shopAddress);
                parameters.put("shopContact", shopContact);
                parameters.put("shopEmail", shopEmail);

                rs = jdbc.getData("select name,status from user where user_id = '" + UserLogin.userID + "';");
                if (rs.next()) {
                    boolean status = rs.getBoolean("status");
                    if (status) {
                        parameters.put("user", rs.getString("name"));
                    } else {
                        parameters.put("user", rs.getString("name") + "(DELETED)");
                    }
                }

                parameters.put("RCount", rows.length);

                JasperPrint jp = JasperFillManager.fillReport(jr, parameters, new JRTableModelDataSource(hiddenTable.getModel()));
                JasperViewer.viewReport(jp, false);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        
            int R=jTable1.getSelectedRow();
            String N=jTable1.getValueAt(R, 1).toString();
            
            if(!(N.equals(""))){
                String SQL="select * from customer where status='1' and custoemer_nic='"+N+"'";
                try {
                    ResultSet RS=jdbc.getData(SQL);
                    if(RS.next()){
                        new NewLoan(N).setVisible(true);
                    
                    }else{
                        JOptionPane.showMessageDialog(this, "Customer Data Not Available Please Add That First ");
                        new Customer().setVisible(true);
                        
                    }
                } catch (Exception e) {
                    System.out.println(e);
                }
            }else{
                JOptionPane.showMessageDialog(this,"Please Update NIC First !");
            }
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    int row;
    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
       if (evt.getButton() == 3) {
            row = jTable1.getSelectedRow();
        }
    }//GEN-LAST:event_jTable1MousePressed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
         if (!(row < 0)) {
            if (evt.isPopupTrigger()) {

                table_popup.show(jTable1, evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jTable1MouseReleased

    private void hiddenTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hiddenTableMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_hiddenTableMousePressed

    private void hiddenTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hiddenTableMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_hiddenTableMouseReleased

    private void hiddenTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hiddenTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_hiddenTableMouseClicked

    private void jMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseClicked
        if(evt.getButton()==1){
            
            
        
        }
    }//GEN-LAST:event_jMenuItem3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Past.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Past.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Past.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Past.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new WindowsLookAndFeel());
                } catch (Exception e) {
                }
                new Past().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField city;
    private javax.swing.JTextField contact1;
    private javax.swing.JTextField contact2;
    private javax.swing.JTextField contact3;
    private javax.swing.JTextField date;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fname;
    private javax.swing.JTable hiddenTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField keyword;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField loneamount;
    private javax.swing.JTextField loneid;
    private javax.swing.JTextField lonerange;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mname;
    private javax.swing.JTextField nic;
    private javax.swing.JTextField no;
    private javax.swing.JTextField paidamount;
    private javax.swing.JTextField special;
    private javax.swing.JTextField street;
    private javax.swing.JPopupMenu table_popup;
    private javax.swing.JTextField totalplusint;
    private javax.swing.JScrollPane val;
    // End of variables declaration//GEN-END:variables
}
