/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import finance.digana.Helper;
import finance.digana.JDBC;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import loan.checkLoanPayments;

/**
 *
 * @author Teran Weerasinghe
 */
public class UserLogin extends javax.swing.JFrame {

    public static ArrayList<String> userPrivilage;
    int xmouse, ymouse;
    public static int userID = 000;
    public static String loginID;

    /**
     * Creates new form UserLogin
     */
    public UserLogin() {
        initComponents();

        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/userLoginIcon.png")));

        un.setCaretColor(Color.white);
        pw.setCaretColor(Color.white);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        un = new javax.swing.JTextField();
        pw = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Login");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setToolTipText("Minimize");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 14, 24, 24));

        jLabel3.setToolTipText("Close");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 14, 24, 24));

        un.setBackground(new java.awt.Color(26, 72, 79));
        un.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        un.setForeground(new java.awt.Color(255, 255, 255));
        un.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        un.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 58, 58), 0));
        getContentPane().add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 228, 270, 30));

        pw.setBackground(new java.awt.Color(26, 72, 79));
        pw.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        pw.setForeground(new java.awt.Color(255, 255, 255));
        pw.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pw.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 72, 79), 0));
        pw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pwMousePressed(evt);
            }
        });
        pw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwKeyPressed(evt);
            }
        });
        getContentPane().add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 262, 270, 30));

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 368, 295, 46));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LoginBackground.jpg"))); // NOI18N
        jLabel1.setText("        ");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 359, -1));

        setSize(new java.awt.Dimension(359, 485));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered

        jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/buttonFocus.jpg")));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited

        jLabel2.setIcon(null);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        setLocation(evt.getXOnScreen() - xmouse, evt.getYOnScreen() - ymouse);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        jLabel3.setIcon(new ImageIcon(getClass().getResource("/img/closeBackground.jpg")));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        jLabel3.setIcon(null);
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/img/minimizeBackground.jpg")));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setIcon(null);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        if (evt.getButton() == 1) {

            System.exit(0);

        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        if (evt.getButton() == 1) {

            this.setState(ICONIFIED);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        if (evt.getButton() == 1) {
            login();
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void pwMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwMousePressed

    }//GEN-LAST:event_pwMousePressed

    private void pwKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwKeyPressed
        if (evt.getKeyCode() == 10) {
            login();
        }
    }//GEN-LAST:event_pwKeyPressed
    private void login() {
        String username = un.getText();
        String password = String.copyValueOf(pw.getPassword());

        if (username.replaceAll(" ", "").isEmpty() || password.replaceAll(" ", "").isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter UserName & Password", "Info", JOptionPane.OK_OPTION);
        } else {
            String sql = "select user_id from user where binary username='" + username + "' and binary password='" + password + "' and status = '1' ;";
            JDBC jdbc = JDBC.getInstance();
            try {
                ResultSet rs = jdbc.getData(sql);

                boolean flag = true;
                while (rs.next()) {
                    flag = false;
                    userID = rs.getInt("user_id");

                    String time = Helper.getDateAndTime("time");
                    String date = Helper.getDateAndTime("date");

                    sql = "insert into login_details (loged_time_date, log_out_date_time, logDate, user_id) values ('" + time + "','" + time + "','" + date + "','" + userID + "') ";

                    int status = jdbc.putData(sql);
                    if (status == 1) {
                        sql = "SELECT MAX(login_details_id) AS LastID FROM login_details;";
                        rs = jdbc.getData(sql);
                        while (rs.next()) {
                            loginID = rs.getString("LastID");
                            break;
                        }

                        userPrivilage = new ArrayList<>();
                        //loadUI(rs, jdbc, userID, userPrivilage);
                        userPrivilage.clear();
                        rs = jdbc.getData("select interface_id from privilages where user_id='" + userID + "' ");
                        while (rs.next()) {
                            int interfaceID = rs.getInt("interface_id");
                            ResultSet resultSet = jdbc.getData("select interface_name from interface where interface_id='" + interfaceID + "' ");
                           if (resultSet.next()) {
                               userPrivilage.add(resultSet.getString("interface_name"));
                           }

                       }

                        System.out.println(userPrivilage.toString());
                        new checkLoanPayments().mainRun();
                        this.dispose();
                        Home.h.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "Try Again!", "Info", JOptionPane.OK_OPTION);
                    }

                    break;
                }
                if (flag) {
                    JOptionPane.showMessageDialog(this, "Incorrect UserName Or Password", "Info", JOptionPane.OK_OPTION);
                }

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }

    public static void loadUI(ResultSet rs, JDBC jdbc, int userid, ArrayList uPri) {
        try {
            rs = jdbc.getData("select interface_id from privilages where user_id='" + userid + "' ");
            while (rs.next()) {
                int interfaceID = rs.getInt("interface_id");
                ResultSet resultSet = jdbc.getData("select interface_name from interface where interface_id='" + interfaceID + "' ");
                if (resultSet.next()) {
                    uPri.add(resultSet.getString("interface_name"));
                }

            }
        } catch (Exception e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField pw;
    private javax.swing.JTextField un;
    // End of variables declaration//GEN-END:variables
}
